name: firebase_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  quickalert: ^1.1.0
  image_picker: ^1.1.2
  path_provider: ^2.0.15
  sqflite: ^2.4.2
  async: ^2.12.0
  shared_preferences: ^2.5.3
  image: ^4.5.4
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.5.3
  firebase_storage: ^12.1.3
  firebase_analytics: ^11.4.6
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  brasil_fields: ^1.18.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/firebase.png"

flutter:
  uses-material-design: true
